language: node_js
node_js:
  - "10.12"
services:
  - redis-server
install:
  - npm install
  - npm install -g codecov
script: "npm test"
after_success:
  - npm run coverage
  - npm run report-coverage
